version: '2'

services:

    app:
      build: ${APP_CODE_PATH_HOST}
      volumes:
          - ${APP_CODE_PATH_HOST}:/var/www
          - ${APP_CODE_PATH_HOST}/storage/app:/var/www/storage/app
          - ${APP_CODE_PATH_HOST}/storage/logs:/var/www/storage/logs
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      links:
        - mysql:3306

    mysql:
      image: mysql:${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - "${MYSQL_PORT}:3306"